<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TmCitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $citys = [
            ['id' => 1, 'code' => '0101', 'name' => 'KAB. KEP SERIBU', 'code_province' => '01', 'active' => 'Y', 'created_at' => now()],
            ['id' => 2, 'code' => '0160', 'name' => 'KOTA JAKARTA PUSAT', 'code_province' => '01', 'active' => 'Y', 'created_at' => now()],
            ['id' => 3, 'code' => '0161', 'name' => 'KOTA JAKARTA UTARA', 'code_province' => '01', 'active' => 'Y', 'created_at' => now()],
            ['id' => 4, 'code' => '0162', 'name' => 'KOTA JAKARTA BARAT', 'code_province' => '01', 'active' => 'Y', 'created_at' => now()],
            ['id' => 5, 'code' => '0163', 'name' => 'KOTA JAKARTA SELATAN', 'code_province' => '01', 'active' => 'Y', 'created_at' => now()],
            ['id' => 6, 'code' => '0164', 'name' => 'KOTA JAKARTA TIMUR', 'code_province' => '01', 'active' => 'Y', 'created_at' => now()],
            ['id' => 7, 'code' => '0205', 'name' => 'KAB. BOGOR', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 8, 'code' => '0206', 'name' => 'KAB. SUKABUMI', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 9, 'code' => '0207', 'name' => 'KAB. CIANJUR', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 10, 'code' => '0208', 'name' => 'KAB. BANDUNG', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 11, 'code' => '0210', 'name' => 'KAB. SUMEDANG', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 12, 'code' => '0211', 'name' => 'KAB. GARUT', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 13, 'code' => '0212', 'name' => 'KAB. TASIKMALAYA', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 14, 'code' => '0214', 'name' => 'KAB. CIAMIS', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 15, 'code' => '0215', 'name' => 'KAB. KUNINGAN', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 16, 'code' => '0216', 'name' => 'KAB. MAJALENGKA', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 17, 'code' => '0217', 'name' => 'KAB. CIREBON', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 18, 'code' => '0218', 'name' => 'KAB. INDRAMAYU', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 19, 'code' => '0219', 'name' => 'KAB. SUBANG', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 20, 'code' => '0220', 'name' => 'KAB. PURWAKARTA', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 21, 'code' => '0221', 'name' => 'KAB. KARAWANG', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 22, 'code' => '0222', 'name' => 'KAB. BEKASI', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 23, 'code' => '0223', 'name' => 'KAB. BANDUNG BARAT', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 24, 'code' => '0224', 'name' => 'KAB. PANGANDARAN', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 25, 'code' => '0260', 'name' => 'KOTA BANDUNG', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 26, 'code' => '0261', 'name' => 'KOTA BOGOR', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 27, 'code' => '0262', 'name' => 'KOTA SUKABUMI', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 28, 'code' => '0263', 'name' => 'KOTA CIREBON', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 29, 'code' => '0265', 'name' => 'KOTA BEKASI', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 30, 'code' => '0266', 'name' => 'KOTA DEPOK', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 31, 'code' => '0267', 'name' => 'KOTA CIMAHI', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 32, 'code' => '0268', 'name' => 'KOTA TASIKMALAYA', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 33, 'code' => '0269', 'name' => 'KOTA BANJAR', 'code_province' => '02', 'active' => 'Y', 'created_at' => now()],
            ['id' => 34, 'code' => '0301', 'name' => 'KAB. CILACAP', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 35, 'code' => '0302', 'name' => 'KAB. BANYUMAS', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 36, 'code' => '0303', 'name' => 'KAB. PURBALINGGA', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 37, 'code' => '0304', 'name' => 'KAB. BANJARNEGARA', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 38, 'code' => '0305', 'name' => 'KAB. KEBUMEN', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 39, 'code' => '0306', 'name' => 'KAB. PURWOREJO', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 40, 'code' => '0307', 'name' => 'KAB. WONOSOBO', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 41, 'code' => '0308', 'name' => 'KAB. MAGELANG', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 42, 'code' => '0309', 'name' => 'KAB. BOYOLALI', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 43, 'code' => '0310', 'name' => 'KAB. KLATEN', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 44, 'code' => '0311', 'name' => 'KAB. SUKOHARJO', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 45, 'code' => '0312', 'name' => 'KAB. WONOGIRI', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 46, 'code' => '0313', 'name' => 'KAB. KARANGANYAR', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 47, 'code' => '0314', 'name' => 'KAB. SRAGEN', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 48, 'code' => '0315', 'name' => 'KAB. GROBOGAN', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 49, 'code' => '0316', 'name' => 'KAB. BLORA', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 50, 'code' => '0317', 'name' => 'KAB. REMBANG', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 51, 'code' => '0318', 'name' => 'KAB. PATI', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 52, 'code' => '0319', 'name' => 'KAB. KUDUS', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 53, 'code' => '0320', 'name' => 'KAB. JEPARA', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 54, 'code' => '0321', 'name' => 'KAB. DEMAK', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 55, 'code' => '0322', 'name' => 'KAB. SEMARANG', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 56, 'code' => '0323', 'name' => 'KAB. TEMANGGUNG', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 57, 'code' => '0324', 'name' => 'KAB. KENDAL', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 58, 'code' => '0325', 'name' => 'KAB. BATANG', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 59, 'code' => '0326', 'name' => 'KAB. PEKALONGAN', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 60, 'code' => '0327', 'name' => 'KAB. PEMALANG', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 61, 'code' => '0328', 'name' => 'KAB. TEGAL', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 62, 'code' => '0329', 'name' => 'KAB. BREBES', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 63, 'code' => '0360', 'name' => 'KOTA MAGELANG', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 64, 'code' => '0361', 'name' => 'KOTA SURAKARTA', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 65, 'code' => '0362', 'name' => 'KOTA SALATIGA', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 66, 'code' => '0363', 'name' => 'KOTA SEMARANG', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 67, 'code' => '0364', 'name' => 'KOTA PEKALONGAN', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 68, 'code' => '0365', 'name' => 'KOTA TEGAL', 'code_province' => '03', 'active' => 'Y', 'created_at' => now()],
            ['id' => 69, 'code' => '0401', 'name' => 'KAB. BANTUL', 'code_province' => '04', 'active' => 'Y', 'created_at' => now()],
            ['id' => 70, 'code' => '0402', 'name' => 'KAB. SLEMAN', 'code_province' => '04', 'active' => 'Y', 'created_at' => now()],
            ['id' => 71, 'code' => '0403', 'name' => 'KAB. GUNUNGKIDUL', 'code_province' => '04', 'active' => 'Y', 'created_at' => now()],
            ['id' => 72, 'code' => '0404', 'name' => 'KAB. KULONPROGO', 'code_province' => '04', 'active' => 'Y', 'created_at' => now()],
            ['id' => 73, 'code' => '0460', 'name' => 'KOTA YOGYAKARTA', 'code_province' => '04', 'active' => 'Y', 'created_at' => now()],
            ['id' => 74, 'code' => '0501', 'name' => 'KAB. GRESIK', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 75, 'code' => '0502', 'name' => 'KAB. SIDOARJO', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 76, 'code' => '0503', 'name' => 'KAB. MOJOKERTO', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 77, 'code' => '0504', 'name' => 'KAB. JOMBANG', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 78, 'code' => '0505', 'name' => 'KAB. BOJONEGORO', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 79, 'code' => '0506', 'name' => 'KAB. TUBAN', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 80, 'code' => '0507', 'name' => 'KAB. LAMONGAN', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 81, 'code' => '0508', 'name' => 'KAB. MADIUN', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 82, 'code' => '0509', 'name' => 'KAB. NGAWI', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 83, 'code' => '0510', 'name' => 'KAB. MAGETAN', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 84, 'code' => '0511', 'name' => 'KAB. PONOROGO', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 85, 'code' => '0512', 'name' => 'KAB. PACITAN', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 86, 'code' => '0513', 'name' => 'KAB. KEDIRI', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 87, 'code' => '0514', 'name' => 'KAB. NGANJUK', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 88, 'code' => '0515', 'name' => 'KAB. BLITAR', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 89, 'code' => '0516', 'name' => 'KAB. TULUNGAGUNG', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 90, 'code' => '0517', 'name' => 'KAB. TRENGGALEK', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 91, 'code' => '0518', 'name' => 'KAB. MALANG', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 92, 'code' => '0519', 'name' => 'KAB. PASURUAN', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 93, 'code' => '0520', 'name' => 'KAB. PROBOLINGGO', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 94, 'code' => '0521', 'name' => 'KAB. LUMAJANG', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 95, 'code' => '0522', 'name' => 'KAB. BONDOWOSO', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 96, 'code' => '0523', 'name' => 'KAB. SITUBONDO', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 97, 'code' => '0524', 'name' => 'KAB. JEMBER', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 98, 'code' => '0525', 'name' => 'KAB. BANYUWANGI', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 99, 'code' => '0526', 'name' => 'KAB. PAMEKASAN', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 100, 'code' => '0527', 'name' => 'KAB. SAMPANG', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 101, 'code' => '0528', 'name' => 'KAB. SUMENEP', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 102, 'code' => '0529', 'name' => 'KAB. BANGKALAN', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 103, 'code' => '0560', 'name' => 'KOTA SURABAYA', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 104, 'code' => '0561', 'name' => 'KOTA MALANG', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 105, 'code' => '0562', 'name' => 'KOTA MADIUN', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 106, 'code' => '0563', 'name' => 'KOTA KEDIRI', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 107, 'code' => '0564', 'name' => 'KOTA MOJOKERTO', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 108, 'code' => '0565', 'name' => 'KOTA BLITAR', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 109, 'code' => '0566', 'name' => 'KOTA PASURUAN', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 110, 'code' => '0567', 'name' => 'KOTA PROBOLINGGO', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 111, 'code' => '0568', 'name' => 'KOTA BATU', 'code_province' => '05', 'active' => 'Y', 'created_at' => now()],
            ['id' => 112, 'code' => '0601', 'name' => 'KAB. ACEH BESAR', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 113, 'code' => '0602', 'name' => 'KAB. PIDIE', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 114, 'code' => '0603', 'name' => 'KAB. ACEH UTARA', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 115, 'code' => '0604', 'name' => 'KAB. ACEH TIMUR', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 116, 'code' => '0605', 'name' => 'KAB. ACEH TENGAH', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 117, 'code' => '0606', 'name' => 'KAB. ACEH BARAT', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 118, 'code' => '0607', 'name' => 'KAB. ACEH SELATAN', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 119, 'code' => '0608', 'name' => 'KAB. ACEH TENGGARA', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 120, 'code' => '0611', 'name' => 'KAB. SIMEULUE', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 121, 'code' => '0612', 'name' => 'KAB. BIREUEN', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 122, 'code' => '0613', 'name' => 'KAB. ACEH SINGKIL', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 123, 'code' => '0614', 'name' => 'KAB. ACEH TAMIANG', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 124, 'code' => '0615', 'name' => 'KAB. GAYO LUES', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 125, 'code' => '0616', 'name' => 'KAB. ACEH NAGAN RAYA', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 126, 'code' => '0617', 'name' => 'KAB. ACEH BARAT DAYA', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 127, 'code' => '0618', 'name' => 'KAB. ACEH JAYA', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 128, 'code' => '0619', 'name' => 'KAB. BENER MERIAH', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 129, 'code' => '0622', 'name' => 'KAB. PIDIE JAYA', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 130, 'code' => '0660', 'name' => 'KOTA SABANG', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 131, 'code' => '0661', 'name' => 'KOTA BANDA ACEH', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 132, 'code' => '0662', 'name' => 'KOTA LHOKSEUMAWE', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 133, 'code' => '0663', 'name' => 'KOTA LANGSA', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 134, 'code' => '0664', 'name' => 'KOTA SUBULUSSALAM', 'code_province' => '06', 'active' => 'Y', 'created_at' => now()],
            ['id' => 135, 'code' => '0701', 'name' => 'KAB. DELI SERDANG', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 136, 'code' => '0702', 'name' => 'KAB. LANGKAT', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 137, 'code' => '0703', 'name' => 'KAB. KARO', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 138, 'code' => '0704', 'name' => 'KAB. SIMALUNGUN', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 139, 'code' => '0705', 'name' => 'KAB. DAIRI', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 140, 'code' => '0706', 'name' => 'KAB. ASAHAN', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 141, 'code' => '0707', 'name' => 'KAB. LABUHAN BATU', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 142, 'code' => '0708', 'name' => 'KAB. TAPANULI UTARA', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 143, 'code' => '0709', 'name' => 'KAB. TAPANULI TENGAH', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 144, 'code' => '0710', 'name' => 'KAB. TAPANULI SELATAN', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 145, 'code' => '0711', 'name' => 'KAB. NIAS', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 146, 'code' => '0712', 'name' => 'KAB. LABUHAN BATU UTARA', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 147, 'code' => '0713', 'name' => 'KAB. LABUHAN BATU SELATAN', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 148, 'code' => '0715', 'name' => 'KAB. MANDAILING NATAL', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 149, 'code' => '0716', 'name' => 'KAB. TOBA SAMOSIR', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 150, 'code' => '0717', 'name' => 'KAB. NIAS SELATAN', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 151, 'code' => '0718', 'name' => 'KAB. PAKPAK BHARAT', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 152, 'code' => '0719', 'name' => 'KAB. HUMBANG HASUNDUTAN', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 153, 'code' => '0720', 'name' => 'KAB. SAMOSIR', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 154, 'code' => '0721', 'name' => 'KAB. SERDANG BEDAGAI', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 155, 'code' => '0722', 'name' => 'KAB. BATUBARA', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 156, 'code' => '0723', 'name' => 'KAB. PADANG LAWAS', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 157, 'code' => '0724', 'name' => 'KAB. PADANG LAWAS UTARA', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 158, 'code' => '0726', 'name' => 'KAB. NIAS UTARA', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 159, 'code' => '0727', 'name' => 'KAB. NIAS BARAT', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 160, 'code' => '0760', 'name' => 'KOTA MEDAN', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 161, 'code' => '0761', 'name' => 'KOTA BINJAI', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 162, 'code' => '0762', 'name' => 'KOTA TEBING TINGGI', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 163, 'code' => '0763', 'name' => 'KOTA PEMATANG SIANTAR', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 164, 'code' => '0764', 'name' => 'KOTA TANJUNG BALAI', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 165, 'code' => '0765', 'name' => 'KOTA SIBOLGA', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 166, 'code' => '0766', 'name' => 'KOTA PADANG SIDIMPUAN', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 167, 'code' => '0767', 'name' => 'KOTA GUNUNGSITOLI', 'code_province' => '07', 'active' => 'Y', 'created_at' => now()],
            ['id' => 168, 'code' => '0801', 'name' => 'KAB. AGAM', 'code_province' => '08', 'active' => 'Y', 'created_at' => now()],
            ['id' => 169, 'code' => '0802', 'name' => 'KAB. PASAMAN', 'code_province' => '08', 'active' => 'Y', 'created_at' => now()],
            ['id' => 170, 'code' => '0803', 'name' => 'KAB. LIMA PULUH KOTA', 'code_province' => '08', 'active' => 'Y', 'created_at' => now()],
            ['id' => 171, 'code' => '0804', 'name' => 'KAB. SOLOK', 'code_province' => '08', 'active' => 'Y', 'created_at' => now()],
            ['id' => 172, 'code' => '0805', 'name' => 'KAB. PADANG PARIAMAN', 'code_province' => '08', 'active' => 'Y', 'created_at' => now()],
            ['id' => 173, 'code' => '0806', 'name' => 'KAB. PESISIR SELATAN', 'code_province' => '08', 'active' => 'Y', 'created_at' => now()],
            ['id' => 174, 'code' => '0807', 'name' => 'KAB. TANAH DATAR', 'code_province' => '08', 'active' => 'Y', 'created_at' => now()],
            ['id' => 175, 'code' => '0808', 'name' => 'KAB. SIJUNJUNG', 'code_province' => '08', 'active' => 'Y', 'created_at' => now()],
            ['id' => 176, 'code' => '0809', 'name' => 'KAB. KEPULAUAN MENTAWAI', 'code_province' => '08', 'active' => 'Y', 'created_at' => now()],
            ['id' => 177, 'code' => '0810', 'name' => 'KAB. PASAMAN BARAT', 'code_province' => '08', 'active' => 'Y', 'created_at' => now()],
            ['id' => 178, 'code' => '0811', 'name' => 'KAB. DHARMASRAYA', 'code_province' => '08', 'active' => 'Y', 'created_at' => now()],
            ['id' => 179, 'code' => '0812', 'name' => 'KAB. SOLOK SELATAN', 'code_province' => '08', 'active' => 'Y', 'created_at' => now()],
            ['id' => 180, 'code' => '0813', 'name' => 'KAB. PARIAMAN PESISIR', 'code_province' => '08', 'active' => 'Y', 'created_at' => now()],
            ['id' => 181, 'code' => '0860', 'name' => 'KOTA BUKITTINGGI', 'code_province' => '08', 'active' => 'Y', 'created_at' => now()],
            ['id' => 182, 'code' => '0861', 'name' => 'KOTA PADANG', 'code_province' => '08', 'active' => 'Y', 'created_at' => now()],
            ['id' => 183, 'code' => '0862', 'name' => 'KOTA PADANG PANJANG', 'code_province' => '08', 'active' => 'Y', 'created_at' => now()],
            ['id' => 184, 'code' => '0863', 'name' => 'KOTA SAWAHLUNTO', 'code_province' => '08', 'active' => 'Y', 'created_at' => now()],
            ['id' => 185, 'code' => '0864', 'name' => 'KOTA SOLOK', 'code_province' => '08', 'active' => 'Y', 'created_at' => now()],
            ['id' => 186, 'code' => '0865', 'name' => 'KOTA PAYAKUMBUH', 'code_province' => '08', 'active' => 'Y', 'created_at' => now()],
            ['id' => 187, 'code' => '0866', 'name' => 'KOTA PARIAMAN', 'code_province' => '08', 'active' => 'Y', 'created_at' => now()],
            ['id' => 188, 'code' => '0901', 'name' => 'KAB. KAMPAR', 'code_province' => '09', 'active' => 'Y', 'created_at' => now()],
            ['id' => 189, 'code' => '0902', 'name' => 'KAB. BENGKALIS', 'code_province' => '09', 'active' => 'Y', 'created_at' => now()],
            ['id' => 190, 'code' => '0903', 'name' => 'KAB. KEPULAUAN MERANTI', 'code_province' => '09', 'active' => 'Y', 'created_at' => now()],
            ['id' => 191, 'code' => '0904', 'name' => 'KAB. INDRAGIRI HULU', 'code_province' => '09', 'active' => 'Y', 'created_at' => now()],
            ['id' => 192, 'code' => '0905', 'name' => 'KAB. INDRAGIRI HILIR', 'code_province' => '09', 'active' => 'Y', 'created_at' => now()],
            ['id' => 193, 'code' => '0908', 'name' => 'KAB. PELALAWAN', 'code_province' => '09', 'active' => 'Y', 'created_at' => now()],
            ['id' => 194, 'code' => '0909', 'name' => 'KAB. ROKAN HULU', 'code_province' => '09', 'active' => 'Y', 'created_at' => now()],
            ['id' => 195, 'code' => '0910', 'name' => 'KAB. ROKAN HILIR', 'code_province' => '09', 'active' => 'Y', 'created_at' => now()],
            ['id' => 196, 'code' => '0911', 'name' => 'KAB. SIAK', 'code_province' => '09', 'active' => 'Y', 'created_at' => now()],
            ['id' => 197, 'code' => '0914', 'name' => 'KAB. KUANTAN SINGINGI', 'code_province' => '09', 'active' => 'Y', 'created_at' => now()],
            ['id' => 198, 'code' => '0960', 'name' => 'KOTA PEKANBARU', 'code_province' => '09', 'active' => 'Y', 'created_at' => now()],
            ['id' => 199, 'code' => '0962', 'name' => 'KOTA DUMAI', 'code_province' => '09', 'active' => 'Y', 'created_at' => now()],
            ['id' => 200, 'code' => '1001', 'name' => 'KAB. BATANGHARI', 'code_province' => '10', 'active' => 'Y', 'created_at' => now()],
            ['id' => 201, 'code' => '1002', 'name' => 'KAB. BUNGO', 'code_province' => '10', 'active' => 'Y', 'created_at' => now()],
            ['id' => 202, 'code' => '1003', 'name' => 'KAB. MERANGIN', 'code_province' => '10', 'active' => 'Y', 'created_at' => now()],
            ['id' => 203, 'code' => '1004', 'name' => 'KAB. TANJUNG JABUNG BARAT', 'code_province' => '10', 'active' => 'Y', 'created_at' => now()],
            ['id' => 204, 'code' => '1005', 'name' => 'KAB. KERINCI', 'code_province' => '10', 'active' => 'Y', 'created_at' => now()],
            ['id' => 205, 'code' => '1006', 'name' => 'KAB. MUARO JAMBI', 'code_province' => '10', 'active' => 'Y', 'created_at' => now()],
            ['id' => 206, 'code' => '1007', 'name' => 'KAB. TEBO', 'code_province' => '10', 'active' => 'Y', 'created_at' => now()],
            ['id' => 207, 'code' => '1008', 'name' => 'KAB. SAROLANGUN', 'code_province' => '10', 'active' => 'Y', 'created_at' => now()],
            ['id' => 208, 'code' => '1009', 'name' => 'KAB. TANJUNG JABUNG TIMUR', 'code_province' => '10', 'active' => 'Y', 'created_at' => now()],
            ['id' => 209, 'code' => '1060', 'name' => 'KOTA JAMBI', 'code_province' => '10', 'active' => 'Y', 'created_at' => now()],
            ['id' => 210, 'code' => '1061', 'name' => 'KOTA SUNGAI PENUH', 'code_province' => '10', 'active' => 'Y', 'created_at' => now()],
            ['id' => 211, 'code' => '1101', 'name' => 'KAB. MUSI BANYUASIN', 'code_province' => '11', 'active' => 'Y', 'created_at' => now()],
            ['id' => 212, 'code' => '1102', 'name' => 'KAB. OGAN KOMERING ILIR', 'code_province' => '11', 'active' => 'Y', 'created_at' => now()],
            ['id' => 213, 'code' => '1103', 'name' => 'KAB. OGAN KOMERING ULU', 'code_province' => '11', 'active' => 'Y', 'created_at' => now()],
            ['id' => 214, 'code' => '1104', 'name' => 'KAB. MUARA ENIM', 'code_province' => '11', 'active' => 'Y', 'created_at' => now()],
            ['id' => 215, 'code' => '1105', 'name' => 'KAB. LAHAT', 'code_province' => '11', 'active' => 'Y', 'created_at' => now()],
            ['id' => 216, 'code' => '1106', 'name' => 'KAB. MUSI RAWAS', 'code_province' => '11', 'active' => 'Y', 'created_at' => now()],
            ['id' => 217, 'code' => '1107', 'name' => 'KAB. BANYUASIN', 'code_province' => '11', 'active' => 'Y', 'created_at' => now()],
            ['id' => 218, 'code' => '1108', 'name' => 'KAB. OGAN ILIR', 'code_province' => '11', 'active' => 'Y', 'created_at' => now()],
            ['id' => 219, 'code' => '1109', 'name' => 'KAB. OKU SELATAN', 'code_province' => '11', 'active' => 'Y', 'created_at' => now()],
            ['id' => 220, 'code' => '1110', 'name' => 'KAB. OKU TIMUR', 'code_province' => '11', 'active' => 'Y', 'created_at' => now()],
            ['id' => 221, 'code' => '1111', 'name' => 'KAB. EMPAT LAWANG', 'code_province' => '11', 'active' => 'Y', 'created_at' => now()],
            ['id' => 222, 'code' => '1112', 'name' => 'KAB. PENUKAL ABAB LEMATANG ILIR', 'code_province' => '11', 'active' => 'Y', 'created_at' => now()],
            ['id' => 223, 'code' => '1113', 'name' => 'KAB. MUSI RAWAS UTARA', 'code_province' => '11', 'active' => 'Y', 'created_at' => now()],
            ['id' => 224, 'code' => '1160', 'name' => 'KOTA PALEMBANG', 'code_province' => '11', 'active' => 'Y', 'created_at' => now()],
            ['id' => 225, 'code' => '1161', 'name' => 'KOTA LUBUK LINGGAU', 'code_province' => '11', 'active' => 'Y', 'created_at' => now()],
            ['id' => 226, 'code' => '1162', 'name' => 'KOTA PRABUMULIH', 'code_province' => '11', 'active' => 'Y', 'created_at' => now()],
            ['id' => 227, 'code' => '1164', 'name' => 'KOTA PAGAR ALAM', 'code_province' => '11', 'active' => 'Y', 'created_at' => now()],
            ['id' => 228, 'code' => '1201', 'name' => 'KAB. LAMPUNG SELATAN', 'code_province' => '12', 'active' => 'Y', 'created_at' => now()],
            ['id' => 229, 'code' => '1202', 'name' => 'KAB. LAMPUNG TENGAH', 'code_province' => '12', 'active' => 'Y', 'created_at' => now()],
            ['id' => 230, 'code' => '1203', 'name' => 'KAB. LAMPUNG UTARA', 'code_province' => '12', 'active' => 'Y', 'created_at' => now()],
            ['id' => 231, 'code' => '1204', 'name' => 'KAB. LAMPUNG BARAT', 'code_province' => '12', 'active' => 'Y', 'created_at' => now()],
            ['id' => 232, 'code' => '1205', 'name' => 'KAB. TULANG BAWANG', 'code_province' => '12', 'active' => 'Y', 'created_at' => now()],
            ['id' => 233, 'code' => '1206', 'name' => 'KAB. TANGGAMUS', 'code_province' => '12', 'active' => 'Y', 'created_at' => now()],
            ['id' => 234, 'code' => '1207', 'name' => 'KAB. LAMPUNG TIMUR', 'code_province' => '12', 'active' => 'Y', 'created_at' => now()],
            ['id' => 235, 'code' => '1208', 'name' => 'KAB. WAY KANAN', 'code_province' => '12', 'active' => 'Y', 'created_at' => now()],
            ['id' => 236, 'code' => '1209', 'name' => 'KAB. PESAWARAN', 'code_province' => '12', 'active' => 'Y', 'created_at' => now()],
            ['id' => 237, 'code' => '1210', 'name' => 'KAB. MESUJI', 'code_province' => '12', 'active' => 'Y', 'created_at' => now()],
            ['id' => 238, 'code' => '1211', 'name' => 'KAB. PESISIR BARAT', 'code_province' => '12', 'active' => 'Y', 'created_at' => now()],
            ['id' => 239, 'code' => '1212', 'name' => 'KAB. TULANG BAWANG BARAT', 'code_province' => '12', 'active' => 'Y', 'created_at' => now()],
            ['id' => 240, 'code' => '1260', 'name' => 'KOTA BANDAR LAMPUNG', 'code_province' => '12', 'active' => 'Y', 'created_at' => now()],
            ['id' => 241, 'code' => '1261', 'name' => 'KOTA METRO', 'code_province' => '12', 'active' => 'Y', 'created_at' => now()],
            ['id' => 242, 'code' => '1290', 'name' => 'KAB. PRINGSEWU', 'code_province' => '12', 'active' => 'Y', 'created_at' => now()],
            ['id' => 243, 'code' => '1301', 'name' => 'KAB. SAMBAS', 'code_province' => '13', 'active' => 'Y', 'created_at' => now()],
            ['id' => 244, 'code' => '1302', 'name' => 'KAB. MEMPAWAH', 'code_province' => '13', 'active' => 'Y', 'created_at' => now()],
            ['id' => 245, 'code' => '1303', 'name' => 'KAB. SANGGAU', 'code_province' => '13', 'active' => 'Y', 'created_at' => now()],
            ['id' => 246, 'code' => '1304', 'name' => 'KAB. SINTANG', 'code_province' => '13', 'active' => 'Y', 'created_at' => now()],
            ['id' => 247, 'code' => '1305', 'name' => 'KAB. KAPUAS HULU', 'code_province' => '13', 'active' => 'Y', 'created_at' => now()],
            ['id' => 248, 'code' => '1306', 'name' => 'KAB. KETAPANG', 'code_province' => '13', 'active' => 'Y', 'created_at' => now()],
            ['id' => 249, 'code' => '1307', 'name' => 'KAB. KAYONG UTARA', 'code_province' => '13', 'active' => 'Y', 'created_at' => now()],
            ['id' => 250, 'code' => '1308', 'name' => 'KAB. BENGKAYANG', 'code_province' => '13', 'active' => 'Y', 'created_at' => now()],
            ['id' => 251, 'code' => '1309', 'name' => 'KAB. LANDAK', 'code_province' => '13', 'active' => 'Y', 'created_at' => now()],
            ['id' => 252, 'code' => '1310', 'name' => 'KAB. MELAWI', 'code_province' => '13', 'active' => 'Y', 'created_at' => now()],
            ['id' => 253, 'code' => '1311', 'name' => 'KAB. SEKADAU', 'code_province' => '13', 'active' => 'Y', 'created_at' => now()],
            ['id' => 254, 'code' => '1312', 'name' => 'KAB. KUBU RAYA', 'code_province' => '13', 'active' => 'Y', 'created_at' => now()],
            ['id' => 255, 'code' => '1360', 'name' => 'KOTA PONTIANAK', 'code_province' => '13', 'active' => 'Y', 'created_at' => now()],
            ['id' => 256, 'code' => '1361', 'name' => 'KOTA SINGKAWANG', 'code_province' => '13', 'active' => 'Y', 'created_at' => now()],
            ['id' => 257, 'code' => '1401', 'name' => 'KAB. KAPUAS', 'code_province' => '14', 'active' => 'Y', 'created_at' => now()],
            ['id' => 258, 'code' => '1402', 'name' => 'KAB. BARITO SELATAN', 'code_province' => '14', 'active' => 'Y', 'created_at' => now()],
            ['id' => 259, 'code' => '1403', 'name' => 'KAB. BARITO UTARA', 'code_province' => '14', 'active' => 'Y', 'created_at' => now()],
            ['id' => 260, 'code' => '1404', 'name' => 'KAB. KOTAWARINGIN TIMUR', 'code_province' => '14', 'active' => 'Y', 'created_at' => now()],
            ['id' => 261, 'code' => '1405', 'name' => 'KAB. KOTAWARINGIN BARAT', 'code_province' => '14', 'active' => 'Y', 'created_at' => now()],
            ['id' => 262, 'code' => '1406', 'name' => 'KAB. PULANG PISAU', 'code_province' => '14', 'active' => 'Y', 'created_at' => now()],
            ['id' => 263, 'code' => '1407', 'name' => 'KAB. GUNUNG MAS', 'code_province' => '14', 'active' => 'Y', 'created_at' => now()],
            ['id' => 264, 'code' => '1408', 'name' => 'KAB. BARITO TIMUR', 'code_province' => '14', 'active' => 'Y', 'created_at' => now()],
            ['id' => 265, 'code' => '1409', 'name' => 'KAB. SUKAMARA', 'code_province' => '14', 'active' => 'Y', 'created_at' => now()],
            ['id' => 266, 'code' => '1410', 'name' => 'KAB. KATINGAN', 'code_province' => '14', 'active' => 'Y', 'created_at' => now()],
            ['id' => 267, 'code' => '1411', 'name' => 'KAB. LAMANDAU', 'code_province' => '14', 'active' => 'Y', 'created_at' => now()],
            ['id' => 268, 'code' => '1412', 'name' => 'KAB. SERUYAN', 'code_province' => '14', 'active' => 'Y', 'created_at' => now()],
            ['id' => 269, 'code' => '1413', 'name' => 'KAB. MURUNG RAYA', 'code_province' => '14', 'active' => 'Y', 'created_at' => now()],
            ['id' => 270, 'code' => '1460', 'name' => 'KOTA PALANGKA RAYA', 'code_province' => '14', 'active' => 'Y', 'created_at' => now()],
            ['id' => 271, 'code' => '1501', 'name' => 'KAB. BANJAR', 'code_province' => '15', 'active' => 'Y', 'created_at' => now()],
            ['id' => 272, 'code' => '1502', 'name' => 'KAB. TANAH LAUT', 'code_province' => '15', 'active' => 'Y', 'created_at' => now()],
            ['id' => 273, 'code' => '1503', 'name' => 'KAB. BARITO KUALA', 'code_province' => '15', 'active' => 'Y', 'created_at' => now()],
            ['id' => 274, 'code' => '1504', 'name' => 'KAB. TAPIN', 'code_province' => '15', 'active' => 'Y', 'created_at' => now()],
            ['id' => 275, 'code' => '1505', 'name' => 'KAB. HULU SUNGAI SELATAN', 'code_province' => '15', 'active' => 'Y', 'created_at' => now()],
            ['id' => 276, 'code' => '1506', 'name' => 'KAB. HULU SUNGAI TENGAH', 'code_province' => '15', 'active' => 'Y', 'created_at' => now()],
            ['id' => 277, 'code' => '1507', 'name' => 'KAB. HULU SUNGAI UTARA', 'code_province' => '15', 'active' => 'Y', 'created_at' => now()],
            ['id' => 278, 'code' => '1508', 'name' => 'KAB. TABALONG', 'code_province' => '15', 'active' => 'Y', 'created_at' => now()],
            ['id' => 279, 'code' => '1509', 'name' => 'KAB. KOTABARU', 'code_province' => '15', 'active' => 'Y', 'created_at' => now()],
            ['id' => 280, 'code' => '1510', 'name' => 'KAB. TANAH BUMBU', 'code_province' => '15', 'active' => 'Y', 'created_at' => now()],
            ['id' => 281, 'code' => '1511', 'name' => 'KAB. BALANGAN', 'code_province' => '15', 'active' => 'Y', 'created_at' => now()],
            ['id' => 282, 'code' => '1560', 'name' => 'KOTA BANJARMASIN', 'code_province' => '15', 'active' => 'Y', 'created_at' => now()],
            ['id' => 283, 'code' => '1561', 'name' => 'KOTA BANJARBARU', 'code_province' => '15', 'active' => 'Y', 'created_at' => now()],
            ['id' => 284, 'code' => '1601', 'name' => 'KAB. PASER', 'code_province' => '16', 'active' => 'Y', 'created_at' => now()],
            ['id' => 285, 'code' => '1602', 'name' => 'KAB. KUTAI KARTANEGARA', 'code_province' => '16', 'active' => 'Y', 'created_at' => now()],
            ['id' => 286, 'code' => '1603', 'name' => 'KAB. BERAU', 'code_province' => '16', 'active' => 'Y', 'created_at' => now()],
            ['id' => 287, 'code' => '1604', 'name' => 'KAB. BULUNGAN', 'code_province' => '16', 'active' => 'Y', 'created_at' => now()],
            ['id' => 288, 'code' => '1605', 'name' => 'KAB. MAHAKAM ULU', 'code_province' => '16', 'active' => 'Y', 'created_at' => now()],
            ['id' => 289, 'code' => '1607', 'name' => 'KAB. MALINAU', 'code_province' => '16', 'active' => 'Y', 'created_at' => now()],
            ['id' => 290, 'code' => '1608', 'name' => 'KAB. NUNUKAN', 'code_province' => '16', 'active' => 'Y', 'created_at' => now()],
            ['id' => 291, 'code' => '1609', 'name' => 'KAB. KUTAI BARAT', 'code_province' => '16', 'active' => 'Y', 'created_at' => now()],
            ['id' => 292, 'code' => '1610', 'name' => 'KAB. KUTAI TIMUR', 'code_province' => '16', 'active' => 'Y', 'created_at' => now()],
            ['id' => 293, 'code' => '1611', 'name' => 'KAB. PENAJAM PASER UTARA', 'code_province' => '16', 'active' => 'Y', 'created_at' => now()],
            ['id' => 294, 'code' => '1612', 'name' => 'KAB. TANA TIDUNG', 'code_province' => '16', 'active' => 'Y', 'created_at' => now()],
            ['id' => 295, 'code' => '1660', 'name' => 'KOTA SAMARINDA', 'code_province' => '16', 'active' => 'Y', 'created_at' => now()],
            ['id' => 296, 'code' => '1661', 'name' => 'KOTA BALIKPAPAN', 'code_province' => '16', 'active' => 'Y', 'created_at' => now()],
            ['id' => 297, 'code' => '1662', 'name' => 'KOTA TARAKAN', 'code_province' => '16', 'active' => 'Y', 'created_at' => now()],
            ['id' => 298, 'code' => '1663', 'name' => 'KOTA BONTANG', 'code_province' => '16', 'active' => 'Y', 'created_at' => now()],
            ['id' => 299, 'code' => '1701', 'name' => 'KAB. BOLAANG MONGONDOW', 'code_province' => '17', 'active' => 'Y', 'created_at' => now()],
            ['id' => 300, 'code' => '1702', 'name' => 'KAB. MINAHASA', 'code_province' => '17', 'active' => 'Y', 'created_at' => now()],
            ['id' => 301, 'code' => '1703', 'name' => 'KAB. SANGIHE', 'code_province' => '17', 'active' => 'Y', 'created_at' => now()],
            ['id' => 302, 'code' => '1704', 'name' => 'KAB. KEPL. TALAUD', 'code_province' => '17', 'active' => 'Y', 'created_at' => now()],
            ['id' => 303, 'code' => '1705', 'name' => 'KAB. MINAHASA SELATAN', 'code_province' => '17', 'active' => 'Y', 'created_at' => now()],
            ['id' => 304, 'code' => '1706', 'name' => 'KAB. MINAHASA UTARA', 'code_province' => '17', 'active' => 'Y', 'created_at' => now()],
            ['id' => 305, 'code' => '1707', 'name' => 'KAB. BOLAANG MONGONDOW UTARA', 'code_province' => '17', 'active' => 'Y', 'created_at' => now()],
            ['id' => 306, 'code' => '1708', 'name' => 'KAB. MINAHASA TENGGARA', 'code_province' => '17', 'active' => 'Y', 'created_at' => now()],
            ['id' => 307, 'code' => '1709', 'name' => 'KAB. SITARO', 'code_province' => '17', 'active' => 'Y', 'created_at' => now()],
            ['id' => 308, 'code' => '1710', 'name' => 'KAB. BOLAANG MONGONDOW TIMUR', 'code_province' => '17', 'active' => 'Y', 'created_at' => now()],
            ['id' => 309, 'code' => '1711', 'name' => 'KAB. BOLAANG MONGONDOW SELATAN', 'code_province' => '17', 'active' => 'Y', 'created_at' => now()],
            ['id' => 310, 'code' => '1760', 'name' => 'KOTA MANADO', 'code_province' => '17', 'active' => 'Y', 'created_at' => now()],
            ['id' => 311, 'code' => '1761', 'name' => 'KOTA BITUNG', 'code_province' => '17', 'active' => 'Y', 'created_at' => now()],
            ['id' => 312, 'code' => '1762', 'name' => 'KOTA TOMOHON', 'code_province' => '17', 'active' => 'Y', 'created_at' => now()],
            ['id' => 313, 'code' => '1763', 'name' => 'KOTA KOTAMOBAGU', 'code_province' => '17', 'active' => 'Y', 'created_at' => now()],
            ['id' => 314, 'code' => '1801', 'name' => 'KAB. BANGGAI KEPULAUAN', 'code_province' => '18', 'active' => 'Y', 'created_at' => now()],
            ['id' => 315, 'code' => '1802', 'name' => 'KAB. DONGGALA', 'code_province' => '18', 'active' => 'Y', 'created_at' => now()],
            ['id' => 316, 'code' => '1803', 'name' => 'KAB. POSO', 'code_province' => '18', 'active' => 'Y', 'created_at' => now()],
            ['id' => 317, 'code' => '1804', 'name' => 'KAB. BANGGAI', 'code_province' => '18', 'active' => 'Y', 'created_at' => now()],
            ['id' => 318, 'code' => '1805', 'name' => 'KAB. BUOL', 'code_province' => '18', 'active' => 'Y', 'created_at' => now()],
            ['id' => 319, 'code' => '1806', 'name' => 'KAB. TOLI TOLI', 'code_province' => '18', 'active' => 'Y', 'created_at' => now()],
            ['id' => 320, 'code' => '1807', 'name' => 'KAB. MOROWALI', 'code_province' => '18', 'active' => 'Y', 'created_at' => now()],
            ['id' => 321, 'code' => '1808', 'name' => 'KAB. PARIGI MOUTONG', 'code_province' => '18', 'active' => 'Y', 'created_at' => now()],
            ['id' => 322, 'code' => '1809', 'name' => 'KAB. TOJO UNA-UNA', 'code_province' => '18', 'active' => 'Y', 'created_at' => now()],
            ['id' => 323, 'code' => '1810', 'name' => 'KAB. SIGI', 'code_province' => '18', 'active' => 'Y', 'created_at' => now()],
            ['id' => 324, 'code' => '1811', 'name' => 'KAB. BANGGAI LAUT', 'code_province' => '18', 'active' => 'Y', 'created_at' => now()],
            ['id' => 325, 'code' => '1812', 'name' => 'KAB. MOROWALI UTARA', 'code_province' => '18', 'active' => 'Y', 'created_at' => now()],
            ['id' => 326, 'code' => '1860', 'name' => 'KOTA PALU', 'code_province' => '18', 'active' => 'Y', 'created_at' => now()],
            ['id' => 327, 'code' => '1901', 'name' => 'KAB. MAROS', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 328, 'code' => '1902', 'name' => 'KAB. PANGKAJENE KEPULAUAN', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 329, 'code' => '1903', 'name' => 'KAB. G O W A', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 330, 'code' => '1904', 'name' => 'KAB. TAKALAR', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 331, 'code' => '1905', 'name' => 'KAB. JENEPONTO', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 332, 'code' => '1906', 'name' => 'KAB. BARRU', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 333, 'code' => '1907', 'name' => 'KAB. BONE', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 334, 'code' => '1908', 'name' => 'KAB. WAJO', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 335, 'code' => '1909', 'name' => 'KAB. SOPPENG', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 336, 'code' => '1910', 'name' => 'KAB. BANTAENG', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 337, 'code' => '1911', 'name' => 'KAB. BULUKUMBA', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 338, 'code' => '1912', 'name' => 'KAB. SINJAI', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 339, 'code' => '1913', 'name' => 'KAB. KEPULAUAN SELAYAR', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 340, 'code' => '1914', 'name' => 'KAB. PINRANG', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 341, 'code' => '1915', 'name' => 'KAB. SIDENRENG RAPPANG', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 342, 'code' => '1916', 'name' => 'KAB. ENREKANG', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 343, 'code' => '1917', 'name' => 'KAB. LUWU', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 344, 'code' => '1918', 'name' => 'KAB. TANA TORAJA', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 345, 'code' => '1924', 'name' => 'KAB. LUWU UTARA', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 346, 'code' => '1927', 'name' => 'KAB. LUWU TIMUR', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 347, 'code' => '1928', 'name' => 'KAB. TORAJA UTARA', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 348, 'code' => '1960', 'name' => 'KOTA MAKASSAR', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 349, 'code' => '1961', 'name' => 'KOTA PARE PARE', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 350, 'code' => '1962', 'name' => 'KOTA PALOPO', 'code_province' => '19', 'active' => 'Y', 'created_at' => now()],
            ['id' => 351, 'code' => '2001', 'name' => 'KAB. KONAWE', 'code_province' => '20', 'active' => 'Y', 'created_at' => now()],
            ['id' => 352, 'code' => '2002', 'name' => 'KAB. MUNA', 'code_province' => '20', 'active' => 'Y', 'created_at' => now()],
            ['id' => 353, 'code' => '2003', 'name' => 'KAB. BUTON', 'code_province' => '20', 'active' => 'Y', 'created_at' => now()],
            ['id' => 354, 'code' => '2004', 'name' => 'KAB. KOLAKA', 'code_province' => '20', 'active' => 'Y', 'created_at' => now()],
            ['id' => 355, 'code' => '2005', 'name' => 'KAB. KONAWE SELATAN', 'code_province' => '20', 'active' => 'Y', 'created_at' => now()],
            ['id' => 356, 'code' => '2006', 'name' => 'KAB. KOLAKA UTARA', 'code_province' => '20', 'active' => 'Y', 'created_at' => now()],
            ['id' => 357, 'code' => '2007', 'name' => 'KAB. WAKATOBI', 'code_province' => '20', 'active' => 'Y', 'created_at' => now()],
            ['id' => 358, 'code' => '2008', 'name' => 'KAB. BOMBANA', 'code_province' => '20', 'active' => 'Y', 'created_at' => now()],
            ['id' => 359, 'code' => '2009', 'name' => 'KAB. BUTON UTARA', 'code_province' => '20', 'active' => 'Y', 'created_at' => now()],
            ['id' => 360, 'code' => '2010', 'name' => 'KAB. KONAWE UTARA', 'code_province' => '20', 'active' => 'Y', 'created_at' => now()],
            ['id' => 361, 'code' => '2011', 'name' => 'KAB. KOLAKA TIMUR', 'code_province' => '20', 'active' => 'Y', 'created_at' => now()],
            ['id' => 362, 'code' => '2012', 'name' => 'KAB. KONAWE KEPULAUAN', 'code_province' => '20', 'active' => 'Y', 'created_at' => now()],
            ['id' => 363, 'code' => '2013', 'name' => 'KAB. MUNA BARAT', 'code_province' => '20', 'active' => 'Y', 'created_at' => now()],
            ['id' => 364, 'code' => '2014', 'name' => 'KAB. BUTON SELATAN', 'code_province' => '20', 'active' => 'Y', 'created_at' => now()],
            ['id' => 365, 'code' => '2015', 'name' => 'KAB. BUTON TENGAH', 'code_province' => '20', 'active' => 'Y', 'created_at' => now()],
            ['id' => 366, 'code' => '2060', 'name' => 'KOTA KENDARI', 'code_province' => '20', 'active' => 'Y', 'created_at' => now()],
            ['id' => 367, 'code' => '2061', 'name' => 'KOTA BAU-BAU', 'code_province' => '20', 'active' => 'Y', 'created_at' => now()],
            ['id' => 368, 'code' => '2101', 'name' => 'KAB. MALUKU TENGAH', 'code_province' => '21', 'active' => 'Y', 'created_at' => now()],
            ['id' => 369, 'code' => '2102', 'name' => 'KAB. MALUKU TENGGARA', 'code_province' => '21', 'active' => 'Y', 'created_at' => now()],
            ['id' => 370, 'code' => '2103', 'name' => 'KAB. BURU', 'code_province' => '21', 'active' => 'Y', 'created_at' => now()],
            ['id' => 371, 'code' => '2104', 'name' => 'KAB. MALUKU TENGGARA BARAT', 'code_province' => '21', 'active' => 'Y', 'created_at' => now()],
            ['id' => 372, 'code' => '2105', 'name' => 'KAB. SERAM BAGIAN BARAT', 'code_province' => '21', 'active' => 'Y', 'created_at' => now()],
            ['id' => 373, 'code' => '2106', 'name' => 'KAB. SERAM BAGIAN TIMUR', 'code_province' => '21', 'active' => 'Y', 'created_at' => now()],
            ['id' => 374, 'code' => '2107', 'name' => 'KAB. KEPULAUAN ARU', 'code_province' => '21', 'active' => 'Y', 'created_at' => now()],
            ['id' => 375, 'code' => '2108', 'name' => 'KAB. MALUKU BARAT DAYA', 'code_province' => '21', 'active' => 'Y', 'created_at' => now()],
            ['id' => 376, 'code' => '2109', 'name' => 'KAB. BURU SELATAN', 'code_province' => '21', 'active' => 'Y', 'created_at' => now()],
            ['id' => 377, 'code' => '2160', 'name' => 'KOTA AMBON', 'code_province' => '21', 'active' => 'Y', 'created_at' => now()],
            ['id' => 378, 'code' => '2161', 'name' => 'KOTA TUAL', 'code_province' => '21', 'active' => 'Y', 'created_at' => now()],
            ['id' => 379, 'code' => '2201', 'name' => 'KAB. BULELENG', 'code_province' => '22', 'active' => 'Y', 'created_at' => now()],
            ['id' => 380, 'code' => '2202', 'name' => 'KAB. JEMBRANA', 'code_province' => '22', 'active' => 'Y', 'created_at' => now()],
            ['id' => 381, 'code' => '2203', 'name' => 'KAB. TABANAN', 'code_province' => '22', 'active' => 'Y', 'created_at' => now()],
            ['id' => 382, 'code' => '2204', 'name' => 'KAB. BADUNG', 'code_province' => '22', 'active' => 'Y', 'created_at' => now()],
            ['id' => 383, 'code' => '2205', 'name' => 'KAB. GIANYAR', 'code_province' => '22', 'active' => 'Y', 'created_at' => now()],
            ['id' => 384, 'code' => '2206', 'name' => 'KAB. KLUNGKUNG', 'code_province' => '22', 'active' => 'Y', 'created_at' => now()],
            ['id' => 385, 'code' => '2207', 'name' => 'KAB. BANGLI', 'code_province' => '22', 'active' => 'Y', 'created_at' => now()],
            ['id' => 386, 'code' => '2208', 'name' => 'KAB. KARANG ASEM', 'code_province' => '22', 'active' => 'Y', 'created_at' => now()],
            ['id' => 387, 'code' => '2209', 'name' => 'KOTA DENPASAR', 'code_province' => '22', 'active' => 'Y', 'created_at' => now()],
            ['id' => 388, 'code' => '2301', 'name' => 'KAB. LOMBOK BARAT', 'code_province' => '23', 'active' => 'Y', 'created_at' => now()],
            ['id' => 389, 'code' => '2302', 'name' => 'KAB. LOMBOK TENGAH', 'code_province' => '23', 'active' => 'Y', 'created_at' => now()],
            ['id' => 390, 'code' => '2303', 'name' => 'KAB. LOMBOK TIMUR', 'code_province' => '23', 'active' => 'Y', 'created_at' => now()],
            ['id' => 391, 'code' => '2304', 'name' => 'KAB. SUMBAWA', 'code_province' => '23', 'active' => 'Y', 'created_at' => now()],
            ['id' => 392, 'code' => '2305', 'name' => 'KAB. DOMPU', 'code_province' => '23', 'active' => 'Y', 'created_at' => now()],
            ['id' => 393, 'code' => '2306', 'name' => 'KAB. B I M A', 'code_province' => '23', 'active' => 'Y', 'created_at' => now()],
            ['id' => 394, 'code' => '2307', 'name' => 'KAB. SUMBAWA BARAT', 'code_province' => '23', 'active' => 'Y', 'created_at' => now()],
            ['id' => 395, 'code' => '2308', 'name' => 'KAB. LOMBOK UTARA', 'code_province' => '23', 'active' => 'Y', 'created_at' => now()],
            ['id' => 396, 'code' => '2360', 'name' => 'KOTA MATARAM', 'code_province' => '23', 'active' => 'Y', 'created_at' => now()],
            ['id' => 397, 'code' => '2361', 'name' => 'KOTA BIMA', 'code_province' => '23', 'active' => 'Y', 'created_at' => now()],
            ['id' => 398, 'code' => '2401', 'name' => 'KAB. KUPANG', 'code_province' => '24', 'active' => 'Y', 'created_at' => now()],
            ['id' => 399, 'code' => '2403', 'name' => 'KAB. TIMOR TENGAH SELATAN', 'code_province' => '24', 'active' => 'Y', 'created_at' => now()],
            ['id' => 400, 'code' => '2404', 'name' => 'KAB. TIMOR TENGAH UTARA', 'code_province' => '24', 'active' => 'Y', 'created_at' => now()],
            ['id' => 401, 'code' => '2405', 'name' => 'KAB. B E L U', 'code_province' => '24', 'active' => 'Y', 'created_at' => now()],
            ['id' => 402, 'code' => '2406', 'name' => 'KAB. A L O R', 'code_province' => '24', 'active' => 'Y', 'created_at' => now()],
            ['id' => 403, 'code' => '2407', 'name' => 'KAB. FLORES TIMUR', 'code_province' => '24', 'active' => 'Y', 'created_at' => now()],
            ['id' => 404, 'code' => '2408', 'name' => 'KAB. SIKKA', 'code_province' => '24', 'active' => 'Y', 'created_at' => now()],
            ['id' => 405, 'code' => '2409', 'name' => 'KAB. E N D E', 'code_province' => '24', 'active' => 'Y', 'created_at' => now()],
            ['id' => 406, 'code' => '2410', 'name' => 'KAB. NGADA', 'code_province' => '24', 'active' => 'Y', 'created_at' => now()],
            ['id' => 407, 'code' => '2411', 'name' => 'KAB. MANGGARAI', 'code_province' => '24', 'active' => 'Y', 'created_at' => now()],
            ['id' => 408, 'code' => '2412', 'name' => 'KAB. SUMBA TIMUR', 'code_province' => '24', 'active' => 'Y', 'created_at' => now()],
            ['id' => 409, 'code' => '2413', 'name' => 'KAB. SUMBA BARAT', 'code_province' => '24', 'active' => 'Y', 'created_at' => now()],
            ['id' => 410, 'code' => '2414', 'name' => 'KAB. LEMBATA', 'code_province' => '24', 'active' => 'Y', 'created_at' => now()],
            ['id' => 411, 'code' => '2415', 'name' => 'KAB. ROTE NDAO', 'code_province' => '24', 'active' => 'Y', 'created_at' => now()],
            ['id' => 412, 'code' => '2416', 'name' => 'KAB. MANGGARAI BARAT', 'code_province' => '24', 'active' => 'Y', 'created_at' => now()],
            ['id' => 413, 'code' => '2417', 'name' => 'KAB. NAGAKEO', 'code_province' => '24', 'active' => 'Y', 'created_at' => now()],
            ['id' => 414, 'code' => '2418', 'name' => 'KAB. SUMBA BARAT DAYA', 'code_province' => '24', 'active' => 'Y', 'created_at' => now()],
            ['id' => 415, 'code' => '2419', 'name' => 'KAB. SUMBA TENGAH', 'code_province' => '24', 'active' => 'Y', 'created_at' => now()],
            ['id' => 416, 'code' => '2420', 'name' => 'KAB. MANGGARAI TIMUR', 'code_province' => '24', 'active' => 'Y', 'created_at' => now()],
            ['id' => 417, 'code' => '2421', 'name' => 'KAB. SABU RAIJUA', 'code_province' => '24', 'active' => 'Y', 'created_at' => now()],
            ['id' => 418, 'code' => '2460', 'name' => 'KOTA KUPANG', 'code_province' => '24', 'active' => 'Y', 'created_at' => now()],
            ['id' => 419, 'code' => '2501', 'name' => 'KAB. JAYA PURA', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 420, 'code' => '2502', 'name' => 'KAB. BIAK NUMFOR', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 421, 'code' => '2503', 'name' => 'KAB. KEPULAUAN YAPEN', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 422, 'code' => '2504', 'name' => 'KAB. DEIYAI', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 423, 'code' => '2505', 'name' => 'KAB. DOGIYAI', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 424, 'code' => '2506', 'name' => 'KAB. INTAN JAYA', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 425, 'code' => '2507', 'name' => 'KAB. MERAUKE', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 426, 'code' => '2508', 'name' => 'KAB. JAYAWIJAYA', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 427, 'code' => '2509', 'name' => 'KAB. PANIAI', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 428, 'code' => '2510', 'name' => 'KAB. NABIRE', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 429, 'code' => '2511', 'name' => 'KAB. PUNCAK JAYA', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 430, 'code' => '2512', 'name' => 'KAB. MIMIKA', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 431, 'code' => '2513', 'name' => 'KAB. KEEROM', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 432, 'code' => '2514', 'name' => 'KAB. SARMI', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 433, 'code' => '2515', 'name' => 'KAB. ASMAT', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 434, 'code' => '2516', 'name' => 'KAB. MAPPI', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 435, 'code' => '2517', 'name' => 'KAB. BOVEN DIGOEL', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 436, 'code' => '2518', 'name' => 'KAB. YAHUKIMO', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 437, 'code' => '2519', 'name' => 'KAB. PEGUNUNGAN BINTANG', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 438, 'code' => '2520', 'name' => 'KAB. SUPIORI', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 439, 'code' => '2521', 'name' => 'KAB. LANNY JAYA', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 440, 'code' => '2522', 'name' => 'KAB. WAROPEN', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 441, 'code' => '2523', 'name' => 'KAB. TOLIKARA', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 442, 'code' => '2524', 'name' => 'KAB. MEMBERAMO TENGAH', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 443, 'code' => '2525', 'name' => 'KAB. YALIMO', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 444, 'code' => '2526', 'name' => 'KAB. PUNCAK', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 445, 'code' => '2527', 'name' => 'KAB. MAMBERAMO RAYA', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 446, 'code' => '2528', 'name' => 'KAB. NDUGA', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 447, 'code' => '2560', 'name' => 'KOTA JAYAPURA', 'code_province' => '25', 'active' => 'Y', 'created_at' => now()],
            ['id' => 448, 'code' => '2601', 'name' => 'KAB. BENGKULU UTARA', 'code_province' => '26', 'active' => 'Y', 'created_at' => now()],
            ['id' => 449, 'code' => '2602', 'name' => 'KAB. REJANG LEBONG', 'code_province' => '26', 'active' => 'Y', 'created_at' => now()],
            ['id' => 450, 'code' => '2603', 'name' => 'KAB. BENGKULU SELATAN', 'code_province' => '26', 'active' => 'Y', 'created_at' => now()],
            ['id' => 451, 'code' => '2604', 'name' => 'KAB. MUKO-MUKO', 'code_province' => '26', 'active' => 'Y', 'created_at' => now()],
            ['id' => 452, 'code' => '2605', 'name' => 'KAB. SELUMA', 'code_province' => '26', 'active' => 'Y', 'created_at' => now()],
            ['id' => 453, 'code' => '2606', 'name' => 'KAB. KAUR', 'code_province' => '26', 'active' => 'Y', 'created_at' => now()],
            ['id' => 454, 'code' => '2607', 'name' => 'KAB. LEBONG', 'code_province' => '26', 'active' => 'Y', 'created_at' => now()],
            ['id' => 455, 'code' => '2608', 'name' => 'KAB. KEPAHIANG', 'code_province' => '26', 'active' => 'Y', 'created_at' => now()],
            ['id' => 456, 'code' => '2609', 'name' => 'KAB. BENGKULU TENGAH', 'code_province' => '26', 'active' => 'Y', 'created_at' => now()],
            ['id' => 457, 'code' => '2660', 'name' => 'KOTA BENGKULU', 'code_province' => '26', 'active' => 'Y', 'created_at' => now()],
            ['id' => 458, 'code' => '2701', 'name' => 'KAB. HALMAHERA BARAT', 'code_province' => '27', 'active' => 'Y', 'created_at' => now()],
            ['id' => 459, 'code' => '2702', 'name' => 'KAB. HALMAHERA TENGAH', 'code_province' => '27', 'active' => 'Y', 'created_at' => now()],
            ['id' => 460, 'code' => '2703', 'name' => 'KAB. HALMAHERA UTARA', 'code_province' => '27', 'active' => 'Y', 'created_at' => now()],
            ['id' => 461, 'code' => '2704', 'name' => 'KAB. HALMAHERA SELATAN', 'code_province' => '27', 'active' => 'Y', 'created_at' => now()],
            ['id' => 462, 'code' => '2705', 'name' => 'KAB. KEPULAUAN SULA', 'code_province' => '27', 'active' => 'Y', 'created_at' => now()],
            ['id' => 463, 'code' => '2706', 'name' => 'KAB. HALMAHERA TIMUR', 'code_province' => '27', 'active' => 'Y', 'created_at' => now()],
            ['id' => 464, 'code' => '2707', 'name' => 'KAB. PULAU MOROTAI', 'code_province' => '27', 'active' => 'Y', 'created_at' => now()],
            ['id' => 465, 'code' => '2708', 'name' => 'KAB. TALIABU', 'code_province' => '27', 'active' => 'Y', 'created_at' => now()],
            ['id' => 466, 'code' => '2760', 'name' => 'KOTA TERNATE', 'code_province' => '27', 'active' => 'Y', 'created_at' => now()],
            ['id' => 467, 'code' => '2761', 'name' => 'KOTA TIDORE KEPULAUAN', 'code_province' => '27', 'active' => 'Y', 'created_at' => now()],
            ['id' => 468, 'code' => '2801', 'name' => 'KAB. PANDEGLANG', 'code_province' => '28', 'active' => 'Y', 'created_at' => now()],
            ['id' => 469, 'code' => '2802', 'name' => 'KAB. LEBAK', 'code_province' => '28', 'active' => 'Y', 'created_at' => now()],
            ['id' => 470, 'code' => '2803', 'name' => 'KAB. TANGERANG', 'code_province' => '28', 'active' => 'Y', 'created_at' => now()],
            ['id' => 471, 'code' => '2804', 'name' => 'KAB. SERANG', 'code_province' => '28', 'active' => 'Y', 'created_at' => now()],
            ['id' => 472, 'code' => '2860', 'name' => 'KOTA CILEGON', 'code_province' => '28', 'active' => 'Y', 'created_at' => now()],
            ['id' => 473, 'code' => '2861', 'name' => 'KOTA TANGERANG', 'code_province' => '28', 'active' => 'Y', 'created_at' => now()],
            ['id' => 474, 'code' => '2862', 'name' => 'KOTA SERANG', 'code_province' => '28', 'active' => 'Y', 'created_at' => now()],
            ['id' => 475, 'code' => '2863', 'name' => 'KOTA TANGERANG SELATAN', 'code_province' => '28', 'active' => 'Y', 'created_at' => now()],
            ['id' => 476, 'code' => '2901', 'name' => 'KAB. BANGKA', 'code_province' => '29', 'active' => 'Y', 'created_at' => now()],
            ['id' => 477, 'code' => '2902', 'name' => 'KAB. BELITUNG', 'code_province' => '29', 'active' => 'Y', 'created_at' => now()],
            ['id' => 478, 'code' => '2903', 'name' => 'KAB. BANGKA BARAT', 'code_province' => '29', 'active' => 'Y', 'created_at' => now()],
            ['id' => 479, 'code' => '2904', 'name' => 'KAB. BANGKA TENGAH', 'code_province' => '29', 'active' => 'Y', 'created_at' => now()],
            ['id' => 480, 'code' => '2905', 'name' => 'KAB. BANGKA SELATAN', 'code_province' => '29', 'active' => 'Y', 'created_at' => now()],
            ['id' => 481, 'code' => '2906', 'name' => 'KAB. BELITUNG TIMUR', 'code_province' => '29', 'active' => 'Y', 'created_at' => now()],
            ['id' => 482, 'code' => '2960', 'name' => 'KOTA PANGKAL PINANG', 'code_province' => '29', 'active' => 'Y', 'created_at' => now()],
            ['id' => 483, 'code' => '3001', 'name' => 'KAB. BOALEMO', 'code_province' => '30', 'active' => 'Y', 'created_at' => now()],
            ['id' => 484, 'code' => '3002', 'name' => 'KAB. GORONTALO', 'code_province' => '30', 'active' => 'Y', 'created_at' => now()],
            ['id' => 485, 'code' => '3003', 'name' => 'KAB. POHUWATO', 'code_province' => '30', 'active' => 'Y', 'created_at' => now()],
            ['id' => 486, 'code' => '3004', 'name' => 'KAB. BONEBOLANGO', 'code_province' => '30', 'active' => 'Y', 'created_at' => now()],
            ['id' => 487, 'code' => '3005', 'name' => 'KAB. GORONTALO UTARA', 'code_province' => '30', 'active' => 'Y', 'created_at' => now()],
            ['id' => 488, 'code' => '3060', 'name' => 'KOTA GORONTALO', 'code_province' => '30', 'active' => 'Y', 'created_at' => now()],
            ['id' => 489, 'code' => '3101', 'name' => 'KAB. BINTAN', 'code_province' => '31', 'active' => 'Y', 'created_at' => now()],
            ['id' => 490, 'code' => '3102', 'name' => 'KAB. KARIMUN', 'code_province' => '31', 'active' => 'Y', 'created_at' => now()],
            ['id' => 491, 'code' => '3103', 'name' => 'KAB. NATUNA', 'code_province' => '31', 'active' => 'Y', 'created_at' => now()],
            ['id' => 492, 'code' => '3104', 'name' => 'KAB. LINGGA', 'code_province' => '31', 'active' => 'Y', 'created_at' => now()],
            ['id' => 493, 'code' => '3105', 'name' => 'KAB. KEPULAUAN ANAMBAS', 'code_province' => '31', 'active' => 'Y', 'created_at' => now()],
            ['id' => 494, 'code' => '3160', 'name' => 'KOTA BATAM', 'code_province' => '31', 'active' => 'Y', 'created_at' => now()],
            ['id' => 495, 'code' => '3161', 'name' => 'KOTA TANJUNGPINANG', 'code_province' => '31', 'active' => 'Y', 'created_at' => now()],
            ['id' => 496, 'code' => '3201', 'name' => 'KAB. FAK-FAK', 'code_province' => '32', 'active' => 'Y', 'created_at' => now()],
            ['id' => 497, 'code' => '3202', 'name' => 'KAB. SORONG', 'code_province' => '32', 'active' => 'Y', 'created_at' => now()],
            ['id' => 498, 'code' => '3203', 'name' => 'KAB. MANOKWARI', 'code_province' => '32', 'active' => 'Y', 'created_at' => now()],
            ['id' => 499, 'code' => '3204', 'name' => 'KAB. KAIMANA', 'code_province' => '32', 'active' => 'Y', 'created_at' => now()],
            ['id' => 500, 'code' => '3205', 'name' => 'KAB. SORONG SELATAN', 'code_province' => '32', 'active' => 'Y', 'created_at' => now()],
            ['id' => 501, 'code' => '3206', 'name' => 'KAB. RAJA AMPAT', 'code_province' => '32', 'active' => 'Y', 'created_at' => now()],
            ['id' => 502, 'code' => '3207', 'name' => 'KAB. TELUK BINTUNI', 'code_province' => '32', 'active' => 'Y', 'created_at' => now()],
            ['id' => 503, 'code' => '3208', 'name' => 'KAB. TELUK WONDAMA', 'code_province' => '32', 'active' => 'Y', 'created_at' => now()],
            ['id' => 504, 'code' => '3209', 'name' => 'KAB. MAYBRAT', 'code_province' => '32', 'active' => 'Y', 'created_at' => now()],
            ['id' => 505, 'code' => '3210', 'name' => 'KAB. TAMBRAUW', 'code_province' => '32', 'active' => 'Y', 'created_at' => now()],
            ['id' => 506, 'code' => '3260', 'name' => 'KOTA SORONG', 'code_province' => '32', 'active' => 'Y', 'created_at' => now()],
            ['id' => 507, 'code' => '3301', 'name' => 'KAB. MAMUJU', 'code_province' => '33', 'active' => 'Y', 'created_at' => now()],
            ['id' => 508, 'code' => '3302', 'name' => 'KAB. MAMUJU UTARA', 'code_province' => '33', 'active' => 'Y', 'created_at' => now()],
            ['id' => 509, 'code' => '3303', 'name' => 'KAB. POLEWALI MANDAR', 'code_province' => '33', 'active' => 'Y', 'created_at' => now()],
            ['id' => 510, 'code' => '3304', 'name' => 'KAB. MAMASA', 'code_province' => '33', 'active' => 'Y', 'created_at' => now()],
            ['id' => 511, 'code' => '3305', 'name' => 'KAB. MAJENE', 'code_province' => '33', 'active' => 'Y', 'created_at' => now()],
            ['id' => 512, 'code' => '3306', 'name' => 'KAB. MAMUJU TENGAH', 'code_province' => '33', 'active' => 'Y', 'created_at' => now()],
            ['id' => 513, 'code' => '3401', 'name' => 'KAB. NUNUKAN', 'code_province' => '34', 'active' => 'Y', 'created_at' => now()],
            ['id' => 514, 'code' => '3402', 'name' => 'KAB. MALINAU', 'code_province' => '34', 'active' => 'Y', 'created_at' => now()],
            ['id' => 515, 'code' => '3403', 'name' => 'KAB. BULUNGAN', 'code_province' => '34', 'active' => 'Y', 'created_at' => now()],
            ['id' => 516, 'code' => '3404', 'name' => 'KAB. TANA TIDUNG', 'code_province' => '34', 'active' => 'Y', 'created_at' => now()],
            ['id' => 517, 'code' => '3405', 'name' => 'KOTA TARAKAN', 'code_province' => '34', 'active' => 'Y', 'created_at' => now()],   
        ];

        DB::table('tm_citys')->insert($citys);
    }
}
